esphome:
  name: gea-esphome
  friendly_name: gea-esphome
  name_add_mac_suffix: true

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Allow OTA updates
ota:
  - platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework: 
    type: esp-idf

# External component configuration
external_components:
  - source: github://joshualongenecker/home-assistant-bridge@develop
    components: [ geappliances_bridge ]

# MQTT configuration for Home Assistant
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

# UART configuration for GEA3 communication
uart:
  id: gea3_uart
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 230400

# GE Appliances Bridge component
geappliances_bridge:
  # device_id: "YourDeviceId"  # Optional: Uncomment to use a custom device ID
  uart_id: gea3_uart
  
  # Mode: "subscribe" (default) or "poll"
  # - subscribe: ERDs are pushed from the appliance (lower latency, less network traffic)
  # - poll: ERDs are polled at regular intervals (more reliable, works when subscribe fails)
  # mode: subscribe  # Default mode - leave commented to use subscribe
  # mode: poll  # Uncomment to use polling mode
  
  # poll_interval: 10000  # Polling interval in milliseconds (only used in poll mode, default: 10000 = 10 seconds)
  
  # Examples:
  #
  # Subscribe mode (default - automatically discovers and subscribes to ERD updates):
  # geappliances_bridge:
  #   uart_id: gea3_uart
  #
  # Poll mode with default 10 second interval:
  # geappliances_bridge:
  #   uart_id: gea3_uart
  #   mode: poll
  #
  # Poll mode with custom 30 second interval:
  # geappliances_bridge:
  #   uart_id: gea3_uart
  #   mode: poll
  #   poll_interval: 30000

