substitutions:
  name: zoneline-esphome
  friendly_name: zoneline-esphome

packages:
  esphome.esp_web_tools_example: github://esphome/firmware/esp-web-tools/esp32c3.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  platformio_options:
   board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework: 
    type: esp-idf

api:
  encryption:
    # Generate a key with: esphome run example.yaml
    # Or use: !secret api_encryption_key
    key: "base64-encoded-32-byte-key-here=="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# External component configuration
external_components:
  - source: github://joshualongenecker/home-assistant-bridge@develop
    components: [ geappliances_bridge ]

# MQTT configuration for Home Assistant
# Replace placeholder values with actual credentials or use secrets:
# broker: !secret mqtt_broker
# username: !secret mqtt_username
# password: !secret mqtt_password
mqtt:
  broker: 192.168.1.100  # Replace with your MQTT broker IP
  username: mqtt_user     # Replace with your MQTT username
  password: mqtt_password # Replace with your MQTT password
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

# UART configuration for GEA3 communication
uart:
  id: gea3_uart
  tx_pin: GPIO21 #D6
  rx_pin: GPIO20 #D7
  baud_rate: 230400

# GE Appliances Bridge component
geappliances_bridge:
  # device_id is optional - if not provided, it will be auto-generated from appliance ERDs
  # Format: "ApplianceTypeName_ModelNumber_SerialNumber" (e.g., "Dishwasher_ZL4200ABC_12345678")
  # Appliance type names are parsed from GE Appliances API documentation
  # device_id: "YourDeviceId"  # Optional: Uncomment to use a custom device ID
  uart_id: gea3_uart
