substitutions:
  name: zoneline-esphome
  friendly_name: zoneline-esphome

packages:
  esphome.esp_web_tools_example: github://esphome/firmware/esp-web-tools/esp32c3.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  platformio_options:
   board_build.flash_mode: dio

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework: 
    type: esp-idf

api:
  encryption:
    key: YourKey

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# External component configuration
external_components:
  - source: github://joshualongenecker/home-assistant-bridge@develop
    components: [ geappliances_bridge ]

# MQTT configuration for Home Assistant
mqtt:
  broker: BrokerIp
  username: YourUsername
  password: YourPassword
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

# UART configuration for GEA3 communication
uart:
  id: gea3_uart
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 230400

# GE Appliances Bridge component
geappliances_bridge:
  device_id: "Zoneline"
  uart_id: gea3_uart
  client_address: 0xE4  # Default GEA3 client address
