esphome:
  name: ge-appliance-bridge
  friendly_name: GE Appliance Bridge

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "GE Appliance Bridge"
    password: !secret ap_password

captive_portal:

# MQTT configuration for Home Assistant
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

# UART configuration for GEA3 communication
uart:
  id: gea3_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 230400

# External component configuration
external_components:
  - source: github://joshualongenecker/home-assistant-bridge
    components: [ geappliances_bridge ]

# GE Appliances Bridge component
geappliances_bridge:
  device_id: "my-dishwasher"
  uart_id: gea3_uart
  client_address: 0xE4  # Default GEA3 client address
