/*!
 * @file
 * @brief Compressed Home Assistant MQTT Discovery entity definitions.
 *
 * Chunked compression: each category is split into small independently-
 * compressible chunks. This allows decompression with a small buffer.
 *
 * This file is auto-generated from ha_discovery JSONL files.
 * Do not edit this file manually. Run scripts/compress_ha_discovery.py to regenerate.
 */

#ifndef HA_DISCOVERY_DATA_H
#define HA_DISCOVERY_DATA_H

#include <stdint.h>
#include <stddef.h>

/* Chunk descriptor: offset and compressed size within category data. */
typedef struct {
  uint32_t offset;
  uint16_t size;
} ha_discovery_chunk_t;

/* Category descriptor: name, data pointer, chunk table, and metadata. */
typedef struct {
  const char* name;
  const uint8_t* data;
  const ha_discovery_chunk_t* chunks;
  uint16_t num_chunks;
  uint16_t max_decompressed_chunk;
} ha_discovery_category_t;

// common.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_common[];

// common.jsonl compressed data (19906 bytes from 135835 bytes)
extern const uint8_t ha_discovery_data_common[];

// refrigeration.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_refrigeration[];

// refrigeration.jsonl compressed data (59405 bytes from 406804 bytes)
extern const uint8_t ha_discovery_data_refrigeration[];

// laundry.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_laundry[];

// laundry.jsonl compressed data (186167 bytes from 771513 bytes)
extern const uint8_t ha_discovery_data_laundry[];

// dishwasher.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_dishwasher[];

// dishwasher.jsonl compressed data (36163 bytes from 191156 bytes)
extern const uint8_t ha_discovery_data_dishwasher[];

// waterheater.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_waterheater[];

// waterheater.jsonl compressed data (5246 bytes from 29513 bytes)
extern const uint8_t ha_discovery_data_waterheater[];

// range.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_range[];

// range.jsonl compressed data (124120 bytes from 714745 bytes)
extern const uint8_t ha_discovery_data_range[];

// airconditioning.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_airconditioning[];

// airconditioning.jsonl compressed data (27131 bytes from 149298 bytes)
extern const uint8_t ha_discovery_data_airconditioning[];

// waterfilter.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_waterfilter[];

// waterfilter.jsonl compressed data (676 bytes from 2122 bytes)
extern const uint8_t ha_discovery_data_waterfilter[];

// smallappliance.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_smallappliance[];

// smallappliance.jsonl compressed data (44285 bytes from 251620 bytes)
extern const uint8_t ha_discovery_data_smallappliance[];

// energy.jsonl chunks
extern const ha_discovery_chunk_t ha_discovery_chunk_energy[];

// energy.jsonl compressed data (17662 bytes from 136614 bytes)
extern const uint8_t ha_discovery_data_energy[];

/* Category table */
extern const ha_discovery_category_t ha_discovery_categories[];

extern const uint16_t ha_discovery_category_count;

// FNV-1a hash of all discovery data for change detection.
// Changes when discovery definitions are updated.
#define HA_DISCOVERY_DATA_HASH 0x38e37445u

#endif
