/*!
 * @file
 * @brief Polling bridge implementation for GE Appliances integration
 */

extern "C" {
#include "polling_bridge.h"
#include "tiny_utils.h"
#include "tiny_gea_constants.h"
}

#include <set>

using namespace std;

// GEA3 protocol constants
enum {
  erd_host_address_broadcast = tiny_gea_broadcast_address,
  erd_host_address_default = 0xC0,
  retry_delay = 100,
  appliance_lost_timeout = 60000,
  max_polling_retries = 3
};

enum {
  signal_start = tiny_hsm_signal_user_start,
  signal_timer_expired,
  signal_polling_timer_expired,
  signal_read_failed,
  signal_read_completed,
  signal_mqtt_disconnected,
  signal_appliance_lost,
  signal_write_requested
};

// Forward declarations of ERD lists (generated by Python component)
extern "C" const tiny_erd_t common_erds[];
extern "C" const size_t common_erd_count;
extern "C" const tiny_erd_t energy_erds[];
extern "C" const size_t energy_erd_count;

static void arm_timer(polling_bridge_t* self, tiny_timer_ticks_t ticks)
{
  tiny_timer_start(
    self->timer_group, &self->timer, ticks, self, +[](void* context) {
      tiny_hsm_send_signal(&reinterpret_cast<polling_bridge_t*>(context)->hsm, signal_timer_expired, nullptr);
    });
}

static void arm_polling_timer(polling_bridge_t* self, tiny_timer_ticks_t ticks)
{
  tiny_timer_start(
    self->timer_group, &self->polling_timer, ticks, self, +[](void* context) {
      tiny_hsm_send_signal(&reinterpret_cast<polling_bridge_t*>(context)->hsm, signal_polling_timer_expired, nullptr);
    });
}

static void reset_lost_appliance_timer(polling_bridge_t* self)
{
  tiny_timer_stop(self->timer_group, &self->timer);
  tiny_timer_start(
    self->timer_group, &self->appliance_lost_timer, appliance_lost_timeout, self, +[](void* context) {
      tiny_hsm_send_signal(&reinterpret_cast<polling_bridge_t*>(context)->hsm, signal_appliance_lost, nullptr);
    });
}

static void disarm_timer(polling_bridge_t* self)
{
  tiny_timer_stop(self->timer_group, &self->timer);
}

static set<tiny_erd_t>& erd_set(polling_bridge_t* self)
{
  return *reinterpret_cast<set<tiny_erd_t>*>(self->erd_set);
}

static tiny_hsm_result_t state_top(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data);
static tiny_hsm_result_t state_identify_appliance(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data);
static tiny_hsm_result_t state_add_common_erds(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data);
static tiny_hsm_result_t state_add_energy_erds(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data);
static tiny_hsm_result_t state_polling(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data);

static tiny_hsm_result_t state_top(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data)
{
  polling_bridge_t* self = container_of(polling_bridge_t, hsm, hsm);

  switch(signal) {
    case signal_write_requested: {
      auto args = reinterpret_cast<const mqtt_client_on_write_request_args_t*>(data);
      tiny_gea3_erd_client_write(self->erd_client, &self->request_id, self->erd_host_address, args->erd, args->value, args->size);
    } break;

    case signal_appliance_lost: {
      tiny_hsm_transition(hsm, state_identify_appliance);
    } break;

    default:
      return tiny_hsm_result_signal_deferred;
  }

  return tiny_hsm_result_signal_consumed;
}

static tiny_hsm_result_t state_identify_appliance(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data)
{
  polling_bridge_t* self = container_of(polling_bridge_t, hsm, hsm);
  auto args = reinterpret_cast<const tiny_gea3_erd_client_on_activity_args_t*>(data);

  switch(signal) {
    case tiny_hsm_signal_entry: {
      self->erd_host_address = erd_host_address_broadcast;
    }
      __attribute__((fallthrough));

    case signal_timer_expired: {
      // Read appliance type (ERD 0x0008)
      tiny_gea3_erd_client_read(self->erd_client, &self->request_id, self->erd_host_address, 0x0008);
      arm_timer(self, retry_delay);
      break;
    }
    
    case signal_read_completed: {
      disarm_timer(self);
      reset_lost_appliance_timer(self);
      
      if(args->read_completed.erd == 0x0008) {
        self->erd_host_address = args->address;
        const uint8_t* appliance_type_response = (const uint8_t*)args->read_completed.data;
        self->appliance_type = *appliance_type_response;
        tiny_hsm_transition(hsm, state_add_common_erds);
      }
      break;
    }
    
    case tiny_hsm_signal_exit: {
      disarm_timer(self);
      break;
    }
    
    default:
      return tiny_hsm_result_signal_deferred;
  }

  return tiny_hsm_result_signal_consumed;
}

static bool send_next_read_request(polling_bridge_t* self)
{
  reset_lost_appliance_timer(self);
  self->erd_index++;
  bool more_erds_to_try = (self->erd_index < self->current_erd_list_count);
  
  if(more_erds_to_try) {
    self->request_id++;
    tiny_gea3_erd_client_read(self->erd_client, &self->request_id, self->erd_host_address, self->current_erd_list[self->erd_index]);
    arm_timer(self, retry_delay);
  }
  
  return more_erds_to_try;
}

static void add_erd_to_polling_list(polling_bridge_t* self, tiny_erd_t erd)
{
  // Check if we have space in the polling list
  if(self->polling_list_count >= MAX_POLLING_LIST_SIZE) {
    // Polling list is full, cannot add more ERDs
    return;
  }
  
  if(erd_set(self).find(erd) == erd_set(self).end()) {
    mqtt_client_register_erd(self->mqtt_client, erd);
    erd_set(self).insert(erd);
  }
  
  self->erd_polling_list[self->polling_list_count] = erd;
  self->polling_list_count++;
}

static tiny_hsm_result_t state_add_common_erds(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data)
{
  polling_bridge_t* self = container_of(polling_bridge_t, hsm, hsm);
  auto args = reinterpret_cast<const tiny_gea3_erd_client_on_activity_args_t*>(data);

  switch(signal) {
    case tiny_hsm_signal_entry:
      self->current_erd_list = common_erds;
      self->current_erd_list_count = common_erd_count;
      self->erd_index = 0;
      self->polling_list_count = 0;
      tiny_gea3_erd_client_read(self->erd_client, &self->request_id, self->erd_host_address, self->current_erd_list[self->erd_index]);
      arm_timer(self, retry_delay);
      break;

    case signal_timer_expired:
      if(!send_next_read_request(self)) {
        tiny_hsm_transition(hsm, state_add_energy_erds);
      }
      break;

    case signal_read_completed:
      disarm_timer(self);
      add_erd_to_polling_list(self, args->read_completed.erd);
      mqtt_client_update_erd(
        self->mqtt_client,
        args->read_completed.erd,
        args->read_completed.data,
        args->read_completed.data_size);

      if(!send_next_read_request(self)) {
        tiny_hsm_transition(hsm, state_add_energy_erds);
      }
      break;

    default:
      return tiny_hsm_result_signal_deferred;
  }

  return tiny_hsm_result_signal_consumed;
}

static tiny_hsm_result_t state_add_energy_erds(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data)
{
  polling_bridge_t* self = container_of(polling_bridge_t, hsm, hsm);
  auto args = reinterpret_cast<const tiny_gea3_erd_client_on_activity_args_t*>(data);

  switch(signal) {
    case tiny_hsm_signal_entry:
      self->current_erd_list = energy_erds;
      self->current_erd_list_count = energy_erd_count;
      self->erd_index = 0;

      if(self->current_erd_list_count > 0) {
        tiny_gea3_erd_client_read(self->erd_client, &self->request_id, self->erd_host_address, self->current_erd_list[self->erd_index]);
        arm_timer(self, retry_delay);
      } else {
        // No energy ERDs, transition directly to polling
        tiny_hsm_transition(hsm, state_polling);
      }
      break;

    case signal_timer_expired:
      if(!send_next_read_request(self)) {
        tiny_hsm_transition(hsm, state_polling);
      }
      break;

    case signal_read_completed:
      disarm_timer(self);
      add_erd_to_polling_list(self, args->read_completed.erd);
      mqtt_client_update_erd(
        self->mqtt_client,
        args->read_completed.erd,
        args->read_completed.data,
        args->read_completed.data_size);

      if(!send_next_read_request(self)) {
        tiny_hsm_transition(hsm, state_polling);
      }
      break;

    default:
      return tiny_hsm_result_signal_deferred;
  }

  return tiny_hsm_result_signal_consumed;
}

static void send_next_poll_read_request(polling_bridge_t* self)
{
  if(self->erd_index < self->polling_list_count) {
    self->request_id++;
    tiny_gea3_erd_client_read(self->erd_client, &self->request_id, self->erd_host_address, self->erd_polling_list[self->erd_index]);
    arm_timer(self, retry_delay);
    // Increment index after initiating the async read request.
    // When signal_read_completed is received, erd_index will point to the next ERD,
    // so we use (erd_index - 1) to access the ERD that just completed reading.
    self->erd_index++;
  }
}

static tiny_hsm_result_t state_polling(tiny_hsm_t* hsm, tiny_hsm_signal_t signal, const void* data)
{
  polling_bridge_t* self = container_of(polling_bridge_t, hsm, hsm);
  auto args = reinterpret_cast<const tiny_gea3_erd_client_on_activity_args_t*>(data);

  switch(signal) {
    case tiny_hsm_signal_entry:
      arm_polling_timer(self, self->polling_interval_ms);
      // Intentional fallthrough: Start first poll immediately upon entering state
      __attribute__((fallthrough));

    case signal_timer_expired:
      send_next_poll_read_request(self);
      break;

    case signal_polling_timer_expired:
      if((self->erd_index >= self->polling_list_count) || (self->polling_retries >= max_polling_retries)) {
        self->erd_index = 0;
        self->polling_retries = 0;
        send_next_poll_read_request(self);
      } else {
        self->polling_retries++;
      }
      arm_polling_timer(self, self->polling_interval_ms);
      break;

    case signal_read_completed:
      disarm_timer(self);
      reset_lost_appliance_timer(self);
      // After initiating a read, erd_index is incremented to point to the next ERD.
      // Therefore, the ERD that just completed is at index (erd_index - 1).
      // Verify bounds: erd_index > 0 ensures we have a previous index,
      // and (erd_index - 1) < polling_list_count ensures it's within the array.
      if(self->erd_index > 0 && (self->erd_index - 1) < self->polling_list_count) {
        self->last_erd_polled_successfully = self->erd_polling_list[self->erd_index - 1];
      }
      mqtt_client_update_erd(
        self->mqtt_client,
        args->read_completed.erd,
        args->read_completed.data,
        args->read_completed.data_size);

      send_next_poll_read_request(self);
      break;

    case signal_mqtt_disconnected:
      tiny_hsm_transition(&self->hsm, state_identify_appliance);
      break;

    case tiny_hsm_signal_exit:
      disarm_timer(self);
      break;

    default:
      return tiny_hsm_result_signal_deferred;
  }

  return tiny_hsm_result_signal_consumed;
}

static const tiny_hsm_state_descriptor_t hsm_state_descriptors[] = {
  { .state = state_top, .parent = nullptr },
  { .state = state_identify_appliance, .parent = state_top },
  { .state = state_add_common_erds, .parent = state_top },
  { .state = state_add_energy_erds, .parent = state_top },
  { .state = state_polling, .parent = state_top }
};

static const tiny_hsm_configuration_t hsm_configuration = {
  .states = hsm_state_descriptors,
  .state_count = element_count(hsm_state_descriptors)
};

void polling_bridge_init(
  polling_bridge_t* self,
  tiny_timer_group_t* timer_group,
  i_tiny_gea3_erd_client_t* erd_client,
  i_mqtt_client_t* mqtt_client,
  uint32_t polling_interval_ms)
{
  self->timer_group = timer_group;
  self->erd_client = erd_client;
  self->mqtt_client = mqtt_client;
  self->polling_interval_ms = polling_interval_ms;
  self->erd_set = reinterpret_cast<void*>(new set<tiny_erd_t>());
  self->erd_host_address = erd_host_address_default;
  self->polling_list_count = 0;
  self->polling_retries = 0;
  self->last_erd_polled_successfully = 0;

  tiny_event_subscription_init(
    &self->erd_client_activity_subscription, self, +[](void* context, const void* _args) {
      auto self = reinterpret_cast<polling_bridge_t*>(context);
      auto args = reinterpret_cast<const tiny_gea3_erd_client_on_activity_args_t*>(_args);

      switch(args->type) {
        case tiny_gea3_erd_client_activity_type_read_completed:
          tiny_hsm_send_signal(&self->hsm, signal_read_completed, args);
          break;

        case tiny_gea3_erd_client_activity_type_read_failed:
          tiny_hsm_send_signal(&self->hsm, signal_read_failed, args);
          break;

        case tiny_gea3_erd_client_activity_type_write_completed:
          mqtt_client_update_erd_write_result(self->mqtt_client, args->write_completed.erd, true, 0);
          break;

        case tiny_gea3_erd_client_activity_type_write_failed:
          mqtt_client_update_erd_write_result(self->mqtt_client, args->write_failed.erd, false, args->write_failed.reason);
          break;
      }
    });
  tiny_event_subscribe(tiny_gea3_erd_client_on_activity(erd_client), &self->erd_client_activity_subscription);

  tiny_event_subscription_init(
    &self->mqtt_write_request_subscription, self, +[](void* context, const void* _args) {
      auto self = reinterpret_cast<polling_bridge_t*>(context);
      auto args = reinterpret_cast<const mqtt_client_on_write_request_args_t*>(_args);
      tiny_hsm_send_signal(&self->hsm, signal_write_requested, args);
    });
  tiny_event_subscribe(mqtt_client_on_write_request(mqtt_client), &self->mqtt_write_request_subscription);

  tiny_event_subscription_init(
    &self->mqtt_disconnect_subscription, self, +[](void* context, const void*) {
      auto self = reinterpret_cast<polling_bridge_t*>(context);
      reinterpret_cast<set<tiny_erd_t>*>(self->erd_set)->clear();
      tiny_hsm_send_signal(&self->hsm, signal_mqtt_disconnected, nullptr);
    });
  tiny_event_subscribe(mqtt_client_on_mqtt_disconnect(mqtt_client), &self->mqtt_disconnect_subscription);

  tiny_hsm_init(&self->hsm, &hsm_configuration, state_identify_appliance);
}

void polling_bridge_destroy(polling_bridge_t* self)
{
  delete reinterpret_cast<set<tiny_erd_t>*>(self->erd_set);
}
