esphome:
  name: gea-esphome-test
  friendly_name: gea-esphome-test
  name_add_mac_suffix: true

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Allow OTA updates
ota:
  - platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework: 
    type: esp-idf

# External component configuration
# For CI testing, we use the local component directory
external_components:
  - source:
      type: local
      path: ../components
    components: [ geappliances_bridge ]

# MQTT configuration for Home Assistant
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

# UART configuration for GEA3 communication
uart:
  id: gea3_uart
  tx_pin: GPIO21 #D6 on Xiao ESP32-C3
  rx_pin: GPIO20 #D7 on Xiao ESP32-C3
  baud_rate: 230400

# GE Appliances Bridge component
geappliances_bridge:
  uart_id: gea3_uart
  # device_id: "YourDeviceId"   # Optional: Uncomment to use a custom device ID
  # mode: auto                  # Default: auto   Options: auto, subscribe, poll
  # polling_interval: 10000     # Default: 10000 ms (10 seconds), used when in polling mode
